config/routes.rb
Rails.application.routes.draw do
  
  resources :people do
    collection do
      get :search
      post :search_result
    end
  end

  get ':controller(/:action(/:id(.:format)))'
  
  root to: 'people#index'

end

app/models/activity.rb
class Activity < CrmBase
  PERMITTED_PARAMS = [:attachable_id, :attachable_type, :user_id, :verb, :confidential, :name, :change]
end  

app/models/addr.rb
class Addr < CrmBase
  PERMITTED_PARAMS = [:id, :attachable_id, :attachable_type, :street, :zip, :city, :country, :primary, :atype,
    :strasse, :plz, :ort, :land, :_destroy, :move_addr_id]
  
end

app/models/company.rb
class Company < CrmBase    
  has_many :contact_details, :class_name => 'contact_detail'
  has_many :tasks, :class_name => 'task'
  has_many :protocols, :class_name => 'protocol'
  has_many :activities, :class_name => 'activity'
  has_many :positions, :class_name => 'position'
  has_many :tags, :class_name => 'tag'

  PERMITTED_PARAMS = [:name, :background, :user_id,
      :custom_field_attributes => CustomField::PERMITTED_PARAMS,
      :contact_detail_attributes => ContactDetail::PERMITTED_PARAMS,
      :addrs_attributes => Addr::PERMITTED_PARAMS]
  
end

app/models/contact_detail.rb
class ContactDetail < CrmBase
  PERMITTED_PARAMS = [:type, :attachable_id, :attachable_type, :atype, :primary, :name]
  
end

app/models/crm_base.rb
require 'active_resource'

class CrmBase < ActiveResource::Base
    
  self.site = ENV['SITE']
  #self.user = ENV['USER']
  #self.password = ENV['PASS']
  self.format = :json
  self.include_root_in_json = true 
  
  def self.remote_new options={}
    new(get("new").merge(options.merge(format: :json)))
  end
  
  
  #API KEY Auth for ActiveResscource
  class << self
    def headers
      @headers ||= {}
      @headers['X-apikey'] = ENV['APIKEY']
      @headers
    end
  end
  
end

app/models/custom_field.rb
class CustomField < CrmBase
  PERMITTED_PARAMS = [:attachable_id, :attachable_type, :custom_fields_type_id, :name]
    
end

app/models/deal.rb
  class Deal < CrmBase
    has_many :tasks, :class_name => 'task'
    has_many :protocols, :class_name => 'protocol'
    has_many :activities, :class_name => 'activity'
    has_many :tags, :class_name => 'tag'
    
    PERMITTED_PARAMS = [:company_id, :user_id, :name, :value, :value_type, 
      :target_date, :finished_at, :current_state, :value_count, :description, :currency,
      :person_ids_set => [], :custom_fields_attributes => CustomField::PERMITTED_PARAMS]
    
  end

app/models/person.rb
class Person < CrmBase
    
  has_many :contact_details
  has_many :addrs
  has_many :tasks
  has_many :protocols
  has_many :activities
  has_many :positions
  has_many :companies
  has_many :tags
  has_many :custom_fields
    
  PERMITTED_PARAMS = [:first_name, :name, :background, :user_id, :title, 
    :custom_field_attributes => CustomField::PERMITTED_PARAMS,
    :contact_detail_attributes => ContactDetail::PERMITTED_PARAMS,
    :addrs_attributes => Addr::PERMITTED_PARAMS]
    
  class << self
    #Search for People by name or first name
    def search name, first_name, per_page = 10
      find :all, 
        :from => "/api/people/search.json",
        :per_page => per_page,
        :params => {
        :name => name, :first_name => first_name,
      
        :includes => "companies"
      }
    end
  end
  
  def natural_name
    if self.first_name.blank?
      self.name
    else
      %{#{self.first_name} #{self.name}}
    end
  end
    
end

app/models/position.rb
class Position < CrmBase
  
  PERMITTED_PARAMS = [:account_id, :person_id, :company_id, :name, :department, :primary_function, :former, :atype]
  
  def company 
    Company.find(self.company_id)
  end
  def person
    Person.find(self.person_id)
  end
end

app/models/project.rb
class Project < CrmBase
  has_many :tasks, :class_name => 'task'
  has_many :protocols, :class_name => 'protocol'
  has_many :activities, :class_name => 'activity'
  has_many :tags, :class_name => 'tag'
    
  PERMITTED_PARAMS = [:company_id, :user_id, :deal_id, :name, :target_date, :finished_at, :current_state, :description,
    :person_ids_set => [], :custom_fields_attributes => CustomField::PERMITTED_PARAMS]
    
end

app/models/protocol.rb
  class Protocol < CrmBase
    PERMITTED_PARAMS = [:user_id, :name, :confidential, :content, 
      :type, :badge, :uploaded_files]
  end

app/models/tag.rb
  class Tag < CrmBase
  PERMITTED_PARAMS = [:attachable_id, :attachable_type, :name]
    
  end  

app/models/task.rb
class Task < CrmBase
  PERMITTED_PARAMS = [:user_id, :attachable_id, :attachable_type, :finished,
      :name, :precise_time, :end_time, :fuzzy, :entire_day, :badge]
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  require 'json'

  before_filter :set_object, only: [:show, :edit, :update, :destroy]
  
  # GET /people
  def index
    
    # INCLUDES for people 
    # possible options: positions, companies, tags, tasks, avatar, tels, 
    # emails, ims, sms, homepages, addrs, custom_fields
    
    includes = if params[:includes] == 'selected'
      'tels emails' 
    elsif params[:includes] == 'all'
      'all'
    else
      ''
    end
    
    options = {order: params[:order], includes: includes}
        
    begin      
      @people = Person.find :all, 
        :per_page => params[:per_page] ? params[:per_page] : 10,
        :params => options
    
      respond_to do |format|
        format.html
      end
    rescue ActiveResource::UnauthorizedAccess => e
      render :text => "unauthorized, please check your crm SITE and APIKEY in conf/environments/#{Rails.env}"
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  # GET /people/search
  def search_result
    @people = Person.search params[:name], params[:first_name], params[:per_page] ? params[:per_page] : 10


    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /people/1
  def show    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json # show.html.erb
    end
  end

  # GET /people/new
  def new
    @person = Person.remote_new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create


    @person = Person.new(person_params)
    
    respond_to do |format|
      if @person.save
        format.html { redirect_to(person_path(@person), :notice => 'Person was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /people/1
  def update
  
    respond_to do |format|
      if @person.update(person_params).save
        format.html { redirect_to(person_path(@person), :notice => 'Person was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
  
  
  protected
  
  def set_object    
    @person = Person.find(params[:id], params: {includes: 'companies addrs tags tasks'})
  rescue ActiveResource::UnauthorizedAccess => e
    render :text => "unauthorized, please check your SITE and APIKEY in conf/environments/#{Rails.env}"
  end
  
  def person_params
    params.require(:person).permit(Person::PERMITTED_PARAMS)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>CscrmApiDemo</title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <section class='connected_crm'>
            Connected to: <%= ENV['SITE'] %>, <%= truncate(ENV['APIKEY'], length: 10)  %>
        </section>
        <nav>
            <%= link_to 'People index', people_path() %> | 
            <%= link_to 'People new', new_person_path() %> | 
            <%= link_to 'People search', search_people_path() %> | 
            <%= link_to 'CSCRM API Docu', 'http://42he.com/de/developer/crm', target: '_blank' %>
        </nav>
        <section class='content'>
            <%= yield %>
        </section>
        <footer>
            CentralStationCRM Demo Project by <a href='http://42he.com'>42he</a>.
        </footer>
    </body>
</html>

app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>People#destroy</h1>
<p>Find me in app/views/people/destroy.html.erb</p>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<%= form_for(@person, url: person_path(@person)) do |f| %>

  <%= f.text_field :title, placeholder: 'title' %>
  <%= f.text_field :first_name, placeholder: 'first name' %>
  <%= f.text_field :name, placeholder: 'name' %>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>People#index</h1>

<p>
    Includes: 
    <%= link_to 'without includes, plain person data', people_path() %> | 
    <%= link_to 'with selected includes (tels emails)', people_path(includes: 'selected') %> | 
    <%= link_to 'with all includes', people_path(includes: 'all') %>
</p>

<p>
    Order: 
    <%= link_to 'name ASC', people_path(order: 'name-asc') %> | 
    <%= link_to 'updated_at DESC', people_path(order: 'updated_at-desc') %> | 
    <%= link_to 'created_at ASC', people_path(order: 'created_at-asc') %> 
</p>

<%= content_tag(:ul) do %>
  <% @people.each do |person| %>
    <%#= person["tels"].tels %>
    <%#= person.inspect %>
    <%= content_tag :li do %>
      <%= link_to person.natural_name, person_path(person) %>

      <% if person.respond_to? :emails and person.emails %>
        <br/>
        <%= person.emails.first.try(:name) || '-' %>
      <% end %>

      <% if params[:includes] == 'all' %>
        <br/>
        <%= person.tags.map(&:name).join(',') || '-'%>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/people/new.html.erb
<h1>People#new</h1>

<%= form_for(@person) do |f| %>

  <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
  </p>

  <p>
      <%= f.label :first_name %><br/>
      <%= f.text_field :first_name %>
  </p>
  <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
  </p>
  <%#= render_nested_fields_collection_for_table(f, :positions, @object.positions) %>
  <%#= render_nested_fields_collection_for_table(f, :tels, @object.tels) %>
  <%#= render_nested_fields_collection_for_table(f, :emails, @object.emails) %>
  <%#= render_nested_fields_collection_for_table(f, :homepages, @object.homepages) %>
  <%#= render_nested_fields_collection_for_table(f, :addrs, @object.addrs) do %>

  <%#= content_tag(:div, class: "related_addrs", data: {behavior: "related_addrs_sink"}) do %>
  <%#= related_addr_helper(@object) %>
  <%# end if @object.addrs.select{|addr| addr.persisted?}.empty? %>
  <%# end %>
  <%#= render_nested_fields_collection_for_table(f, :ims, @object.ims) %>
  <%#= render_nested_fields_collection_for_table(f, :sms, @object.sms) %>
  <%#= render_nested_fields_collection_for_table(f, :assis, @object.assis) %>
  <%#= render_nested_fields_collection_for_table(f, :historic_events, @object.historic_events) %>

  <%#= f.collection_select(:user_id, active_users_plus_object_user_helper((f.object and f.object.persisted?) ? f.object.user : nil), :id, :natural_name, 
  :include_blank => true,
  :selected => f.object.persisted? ? f.object.user_id : current_user.id) %>
  <p>
      <%= f.label :background %><br/>
      <%= f.text_area :background, {:rows => 5} %>
  </p>

  <p>
      <%= f.submit %> or <%= link_to 'abort', people_path %>
  </p>
<% end %>

app/views/people/search.html.erb
<h1>People#search</h1>

<%= form_tag search_result_people_path do %>

  <p>
      <%= label_tag :first_name %><br/>
      <%= text_field_tag :first_name %>
  </p>
  <p>
      <%= label_tag :name %><br/>
      <%= text_field_tag :name %>
  </p>
  <%= submit_tag 'find people' %>

<% end %>

app/views/people/search_result.html.erb
<h1>People#search_result</h1>

<%= content_tag(:ul) do %>
  <% @people.each do |person| %>
    <%= content_tag :li do %>
      <%= link_to person.natural_name, person_path(person) %>
      <%= link_to person.companies.first.name if person.companies.any? %>
    <% end %>
  <% end %>
<% end %>

app/views/people/show.html.erb
<%= link_to "back", :back %>

<h1><%= @person.first_name %> <%= @person.name %></h1>

<% @person.attributes.each do |k,v| %>
  <%= k %>: <%= v.is_a?(Array) ? '[...]' : v %><br/>
<% end %>

<h2>Nested attributes</h2>

<% if @person.companies.any? %>
  <h3>Companies</h3>
  <ul>
      <% @person.companies.each do |company| %>  
        <%= content_tag :li, company.name %>
      <% end %>
  </ul>
<% end %>

<% if @person.tags.any? %>
  <h3>Tags</h3>
  <%= @person.tags.map(&:name).join(', ') %>
<% end %>

<% if @person.tasks.any? %>
  <h3>Tasks</h3>
  <ul>
      <% @person.tasks.each do |task| %>  
        <%= content_tag :li, task.name %>
      <% end %>
  </ul>
<% end %>

<% if @person.addrs.any? %>
  <h3>Addrs</h3>
  <ul>
      <% @person.addrs.each do |addr| %>  
        <%= content_tag :li do %>
          <%= addr.street %>
          <%= addr.zip %>
          <%= addr.city %>
        <% end %>
      <% end %>
  </ul>
<% end %>

<% if @person.activities.any? %>
  <h3>Activities</h3>
  <ul>
      <% @person.activities.each do |activity| %>  
        <%= content_tag :li do %>
          <%= activity.created_at.to_date %>
          <%= activity.name %>
          <%= activity.verb %>
        <% end %>
      <% end %>
  </ul>
<% end %>

app/views/people/update.html.erb
<h1>People#update</h1>
<p>Find me in app/views/people/update.html.erb</p>